package cn.com.akl.u8.cxml;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.Vector;

import cn.com.akl.u8.entity.InventoryEntity;
import cn.com.akl.u8.entity.InventoryItemEntity;
import cn.com.akl.u8.util.InterfaceUtil;

/**
 * 
 * @author wjj
 * 
 */
public class InventoryUtil {
	public Map<String, Object> Inventory(
			Vector<Hashtable<String,String>> heads,
			Hashtable<String, String> body) throws Exception {
		Map<String, Object> map = new HashMap<String, Object>();	
		
		// 单头
		List<InventoryEntity> head = new ArrayList<InventoryEntity>();
		for (Hashtable<String, String> ht : heads) {
			InventoryEntity ie = new InventoryEntity();
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
			String ggrq = sdf.format(sdf.parse(ht.get("UPDATEDATE")));// 更改日期
			String cjrq=sdf.format(sdf.parse(ht.get("CREATEDATE")));//创建日期
			
			ie.setCode(ht.get("WLBH"));//物料编号
			ie.setName(ht.get("WLMC"));//名称
			ie.setSpecs(ht.get("XH"));//规格
			ie.setSelf_define1(ht.get("XH"));// 型号
			
			String wlflbh=InterfaceUtil.getU8Number("004",ht.get("LBID"),"");
			ie.setSort_code(wlflbh);//物料大类编码
			String wldwbh=InterfaceUtil.getU8Number("005",ht.get("DW"),"");
			ie.setMain_measure(wldwbh);// 物料计量单位编码
			
			ie.setStart_date(cjrq);
			ie.setSale_flag("1");// ?是否内销
			ie.setPurchase_flag("1");// 是否外购
			ie.setSelfmake_flag("0");
			ie.setProd_consu_flag("0");//
			ie.setIn_making_flag("0");
			ie.setTax_serv_flag("0");
			ie.setSuit_flag("0");
			ie.setTax_rate("0");
			ie.setSelf_define2(ht.get("HZBM"));
			
			ie.setUnit_weight(ht.get("ZL"));//净重
			ie.setUnit_volume(ht.get("TJ"));//体积
			ie.setAdvance_period("0");
			ie.setQlty_guarantee_flag("0");
			ie.setBatch_flag("0");
			ie.setEntrust_flag("0");
			ie.setBacklog_flag("0");
			ie.setDiscount_flag("0");// 是否折扣
			ie.setFree_item1("0");
			ie.setFree_item2("0");
			ie.setModifyPerson(ht.get("UPDATEUSER"));// 变更人
			ie.setModifyDate(ggrq);// 更改日期
			ie.setPricetype("先进先出法");// 计价方式
			ie.setBfixunit("0");
			ie.setBtrack("0");
			ie.setBserial("0");
			ie.setBbarcode("0");
			ie.setFree_item3("0");
			ie.setFree_item4("0");
			ie.setFree_item5("0");
			ie.setFree_item6("0");
			ie.setFree_item7("0");
			ie.setFree_item8("0");
			ie.setFree_item9("0");
			ie.setFree_item10("0");
			ie.setUnitgroup_type("0");
			ie.setUnitgroup_code("1");
			ie.setUnitgroup_name("日常单位");
			ie.setCcomunitname(wldwbh);
			ie.setSolitude("0");
			ie.setSpecialties("0");
			ie.setPropertyCheck("0");
			ie.setRecipeBatch("0");
			ie.setbPlanInv("0");
			ie.setbProxyForeign("0");
			ie.setbATOModel("0");
			ie.setbCheckItem("0");
			ie.setbPTOModel("0");
			ie.setBequipment("0");
			ie.setcPlanMethod("R");//--------
			ie.setbMPS("0");
			ie.setbROP("0");
			ie.setbRePlan("0");
			ie.setcSRPolicy("PE");
			ie.setbBillUnite("0");
			ie.setbCutMantissa("0");
			ie.setbInTotalCost("1");
			ie.setiSupplyType("0");
			ie.setbConfigFree1("0");
			ie.setbConfigFree2("0");
			ie.setbConfigFree3("0");
			ie.setbConfigFree4("0");
			ie.setbConfigFree5("0");
			ie.setbConfigFree6("0");
			ie.setbConfigFree7("0");
			ie.setbConfigFree8("0");
			ie.setbConfigFree9("0");
			ie.setbConfigFree10("0");
			ie.setbOutInvDT("0");
			ie.setbPeriodDT("0");
			ie.setbBackInvDT("0");
			ie.setbDTWarnInv("0");
			ie.setCshopunit(wldwbh);
			ie.setBimportmedicine("0");
			ie.setBfirstbusimedicine("0");
			ie.setBforeexpland("0");
			ie.setFconvertrate("1");
			ie.setBinvmodel("0");
			ie.setBexpsale("1");
			ie.setBcheckbsatp("0");
			ie.setBcheckfree1("0");
			ie.setBcheckfree2("0");
			ie.setBcheckfree3("0");
			ie.setBcheckfree4("0");
			ie.setBcheckfree5("0");
			ie.setBcheckfree6("0");
			ie.setBcheckfree7("0");
			ie.setBcheckfree8("0");
			ie.setBcheckfree9("0");
			ie.setBcheckfree10("0");
			ie.setBbommain("0");
			ie.setBbomsub("0");
			ie.setBproductbill("0");
			ie.setIcheckatp("0");
			ie.setBpiece("0");
			ie.setBsrvitem("0");
			ie.setBsrvfittings("0");
			ie.setBspecialorder("0");
			ie.setBtracksalebill("0");
			ie.setIsurenesstype("1");
			ie.setBinbyprocheck("1");
			ie.setIrequiretrackstyle("0");
			ie.setIbomexpandunittype("1");
			ie.setIexpiratdatecalcu("0");
			ie.setBpurpricefree1("0");
			ie.setBpurpricefree2("0");
			ie.setBpurpricefree3("0");
			ie.setBpurpricefree4("0");
			ie.setBpurpricefree5("0");
			ie.setBpurpricefree6("0");
			ie.setBpurpricefree7("0");
			ie.setBpurpricefree8("0");
			ie.setBpurpricefree9("0");
			ie.setBpurpricefree10("0");
			ie.setBsalepricefree1("0");
			ie.setBsalepricefree2("0");
			ie.setBsalepricefree3("0");
			ie.setBsalepricefree4("0");
			ie.setBsalepricefree5("0");
			ie.setBsalepricefree6("0");
			ie.setBsalepricefree7("0");
			ie.setBsalepricefree8("0");
			ie.setBsalepricefree9("0");
			ie.setBsalepricefree10("0");
			ie.setBbondedinv("0");
			ie.setBbatchcreate("0");
			ie.setBbatchproperty1("0");
			ie.setBbatchproperty2("0");
			ie.setBbatchproperty3("0");
			ie.setBbatchproperty4("0");
			ie.setBbatchproperty5("0");
			ie.setBbatchproperty6("0");
			ie.setBbatchproperty7("0");
			ie.setBbatchproperty8("0");
			ie.setBbatchproperty9("0");
			ie.setBbatchproperty10("0");
			ie.setBcontrolfreerange1("0");
			ie.setBcontrolfreerange2("0");
			ie.setBcontrolfreerange3("0");
			ie.setBcontrolfreerange4("0");
			ie.setBcontrolfreerange5("0");
			ie.setBcontrolfreerange6("0");
			ie.setBcontrolfreerange7("0");
			ie.setBcontrolfreerange8("0");
			ie.setBcontrolfreerange9("0");
			ie.setBcontrolfreerange10("0");
			ie.setIwarrantyunit("0");
			ie.setBinvkeypart("1");
			ie.setIacceptearlydays("999");
			ie.setDinvcreatedatetime(cjrq);//------------------启用日期
			ie.setBpuquota("0");
			ie.setBinvrohs("0");
			ie.setBprjmat("0");
			ie.setBinvasset("0");
			ie.setBsrvproduct("0");
			ie.setIacceptdelaydays("0");
			ie.setiPlanCheckDay("0");
			ie.setIdrawtype("0");
			ie.setbSCkeyProjections("0");
			ie.setiSupplyPeriodType("1");
			ie.setiAvailabilityDate("1");
			ie.setBsuitretail("0");
			ie.setFroundfactor("0");
			ie.setBchecksubitemcost("1");
			ie.setBconsiderfreestock("1");
			ie.setBreceiptbydt("0");
			ie.setBkccutmantissa("0");	
			head.add(ie);
		}
		map.put("head", head);
		
		// 单身
		//List<InventoryItemEntity> inventoryIList = new ArrayList<InventoryItemEntity>();
		//for (Hashtable<String, String> ht : body) {
		//InventoryItemEntity iie = new InventoryItemEntity();
		//iie.setPartid(body.get("0");
		//iie.setInvcode(body.get("WLBH"));
		//iie.setIsurenesstype(body.get("1");
		//map.put("body",iie);
		//map.put("body", inventoryIList);
		return map;
		
		
	}

	public String inventoryXml(Map<String, Object> map) throws Exception {
		List<InventoryEntity> inventoryILists=(List<InventoryEntity>)map.get("head");
		StringBuffer sb=new StringBuffer();
			sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>"+
					"<ufinterface sender=\"222\" receiver=\"u8\" roottag=\"inventory\" docid=\"\" proc=\"add\" codeexchanged=\"N\" exportneedexch=\"N\" paginate=\"0\" display=\"存货档案\" family=\"基础档案\">");
				for(InventoryEntity head:inventoryILists){
					sb.append(
					"<inventory>"+
					"<header>"+
					"<code>"+head.getCode()+"</code>"+
					"<name>"+head.getName()+"</name>"+
					"<InvAddCode/>"+
					"<specs>"+head.getSpecs()+"</specs>"+
					"<sort_code>"+head.getSort_code()+"</sort_code>"+
					"<main_supplier/>"+
					"<main_measure>"+head.getMain_measure()+"</main_measure>"+
					"<switch_item/>"+
					"<inv_position/>"+
					"<sale_flag>1</sale_flag>"+
					"<purchase_flag>1</purchase_flag>"+
					"<selfmake_flag>0</selfmake_flag>"+
					"<prod_consu_flag>0</prod_consu_flag>"+
					"<in_making_flag>0</in_making_flag>"+
					"<tax_serv_flag>0</tax_serv_flag>"+
					"<suit_flag>0</suit_flag>"+
					"<tax_rate>0</tax_rate>"+
					"<unit_weight>"+head.getUnit_weight()+"</unit_weight>"+
					"<unit_volume>"+head.getUnit_volume()+"</unit_volume>"+
					"<pro_sale_price/>"+
					"<ref_cost/>"+
					"<ref_sale_price/>"+
					"<bottom_sale_price/>"+
					"<new_cost/>"+
					"<advance_period>0</advance_period>"+
					"<ecnomic_batch/>"+
					"<safe_stock/>"+
					"<top_stock/>"+
					"<bottom_stock/>"+
					"<backlog/>"+
					"<ABC_type/>"+
					"<qlty_guarantee_flag>0</qlty_guarantee_flag>"+
					"<batch_flag>0</batch_flag>"+
					"<entrust_flag>0</entrust_flag>"+
					"<backlog_flag>0</backlog_flag>"+
					"<start_date>"+head.getStart_date()+"</start_date>"+
					"<end_date/>"+
					"<free_item1>0</free_item1>"+
					"<free_item2>0</free_item2>"+
					"<self_define1>"+head.getSelf_define1()+"</self_define1>"+
					"<self_define2>"+head.getSelf_define2()+"</self_define2>"+
					"<self_define3/>"+
					"<discount_flag>0</discount_flag>"+
					"<top_source_price/>"+
					"<quality/>"+
					"<retailprice/>"+
					"<price1/>"+
					"<price2/>"+
					"<price3/>"+
					"<CreatePerson/>"+
					"<ModifyPerson>"+head.getModifyPerson()+"</ModifyPerson>"+
					"<ModifyDate>"+head.getModifyDate()+"</ModifyDate>"+
					"<subscribe_point/>"+
					"<avgquantity/>"+
					"<pricetype>先进先出法</pricetype>"+
					"<bfixunit>0</bfixunit>"+
					"<outline/>"+
					"<inline/>"+
					"<overdate/>"+
					"<warndays/>"+
					"<expense_rate/>"+
					"<btrack>0</btrack>"+
					"<bserial>0</bserial>"+
					"<bbarcode>0</bbarcode>"+
					"<barcode/>"+
					"<auth_class/>"+
					"<self_define4/>"+
					"<self_define5/>"+
					"<self_define6/>"+
					"<self_define7/>"+
					"<self_define8/>"+
					"<self_define9/>"+
					"<self_define10/>"+
					"<self_define11/>"+
					"<self_define12/>"+
					"<self_define13/>"+
					"<self_define14/>"+
					"<self_define15/>"+
					"<self_define16/>"+
					"<free_item3>0</free_item3>"+
					"<free_item4>0</free_item4>"+
					"<free_item5>0</free_item5>"+
					"<free_item6>0</free_item6>"+
					"<free_item7>0</free_item7>"+
					"<free_item8>0</free_item8>"+
					"<free_item9>0</free_item9>"+
					"<free_item10>0</free_item10>"+
					"<unitgroup_type>0</unitgroup_type>"+
					"<unitgroup_code>1</unitgroup_code>"+
					"<puunit_code/>"+
					"<saunit_code/>"+
					"<stunit_code/>"+
					"<caunit_code/>"+
					"<unitgroup_name>"+head.getUnitgroup_name()+"</unitgroup_name>"+
					"<ccomunitname>"+head.getCcomunitname()+"</ccomunitname>"+
					"<puunit_name/>"+
					"<saunit_name/>"+
					"<stunit_name/>"+
					"<caunit_name/>"+
					"<puunit_ichangrate/>"+
					"<saunit_ichangrate/>"+
					"<stunit_ichangrate/>"+
					"<caunit_ichangrate/>"+
					"<check_frequency/>"+
					"<frequency/>"+
					"<check_day/>"+
					"<lastcheck_date/>"+
					"<wastage/>"+
					"<solitude>0</solitude>"+
					"<enterprise/>"+
					"<address/>"+
					"<file/>"+
					"<brand/>"+
					"<checkout_no/>"+
					"<licence/>"+
					"<specialties>0</specialties>"+
					"<defwarehouse/>"+
					"<salerate/>"+
					"<advanceDate/>"+
					"<currencyName/>"+
					"<ProduceAddress/>"+
					"<produceNation/>"+
					"<RegisterNo/>"+
					"<EnterNo/>"+
					"<PackingType/>"+
					"<EnglishName/>"+
					"<PropertyCheck>0</PropertyCheck>"+
					"<PreparationType/>"+
					"<Commodity/>"+
					"<RecipeBatch>0</RecipeBatch>"+
					"<NotPatentName/>"+
					"<cAssComunitCode/>"+
					"<ROPMethod/>"+
					"<SubscribePoint/>"+
					"<BatchRule/>"+
					"<AssureProvideDays/>"+
					"<VagQuantity/>"+
					"<TestStyle/>"+
					"<DTMethod/>"+
					"<DTRate/>"+
					"<DTNum/>"+
					"<DTUnit/>"+
					"<DTStyle/>"+
					"<QTMethod/>"+
					"<bPlanInv>0</bPlanInv>"+
					"<bProxyForeign>0</bProxyForeign>"+
					"<bATOModel>0</bATOModel>"+
					"<bCheckItem>0</bCheckItem>"+
					"<bPTOModel>0</bPTOModel>"+
					"<bequipment>0</bequipment>"+
					"<cProductUnit/>"+
					"<fOrderUpLimit/>"+
					"<cMassUnit/>"+
					"<fRetailPrice/>"+
					"<cInvDepCode/>"+
					"<iAlterAdvance/>"+
					"<fAlterBaseNum/>"+
					"<cPlanMethod>R</cPlanMethod>"+
					"<bMPS>0</bMPS>"+
					"<bROP>0</bROP>"+
					"<bRePlan>0</bRePlan>"+
					"<cSRPolicy>PE</cSRPolicy>"+
					"<bBillUnite>0</bBillUnite>"+
					"<iSupplyDay/>"+
					"<fSupplyMulti/>"+
					"<fMinSupply/>"+
					"<bCutMantissa>0</bCutMantissa>"+
					"<cInvPersonCode/>"+
					"<iInvTfId/>"+
					"<cEngineerFigNo/>"+
					"<bInTotalCost>1</bInTotalCost>"+
					"<iSupplyType>0</iSupplyType>"+
					"<bConfigFree1>0</bConfigFree1>"+
					"<bConfigFree2>0</bConfigFree2>"+
					"<bConfigFree3>0</bConfigFree3>"+
					"<bConfigFree4>0</bConfigFree4>"+
					"<bConfigFree5>0</bConfigFree5>"+
					"<bConfigFree6>0</bConfigFree6>"+
					"<bConfigFree7>0</bConfigFree7>"+
					"<bConfigFree8>0</bConfigFree8>"+
					"<bConfigFree9>0</bConfigFree9>"+
					"<bConfigFree10>0</bConfigFree10>"+
					"<iDTLevel/>"+
					"<cDTAQL/>"+
					"<bOutInvDT>0</bOutInvDT>"+
					"<bPeriodDT>0</bPeriodDT>"+
					"<cDTPeriod/>"+
					"<bBackInvDT>0</bBackInvDT>"+
					"<iEndDTStyle/>"+
					"<bDTWarnInv>0</bDTWarnInv>"+
					"<fBackTaxRate/>"+
					"<cCIQCode/>"+
					"<cWGroupCode/>"+
					"<cWUnit/>"+
					"<fGrossW/>"+
					"<cVGroupCode/>"+
					"<cVUnit/>"+
					"<fLength/>"+
					"<fWidth/>"+
					"<fHeight/>"+
					"<cpurpersoncode/>"+
					"<iBigMonth/>"+
					"<iBigDay/>"+
					"<iSmallMonth/>"+
					"<iSmallDay/>"+
					"<cshopunit>"+head.getCshopunit()+"</cshopunit>"+
					"<bimportmedicine>0</bimportmedicine>"+
					"<bfirstbusimedicine>0</bfirstbusimedicine>"+
					"<bforeexpland>0</bforeexpland>"+
					"<cinvplancode/>"+
					"<fconvertrate>1</fconvertrate>"+
					"<dreplacedate/>"+
					"<binvmodel>0</binvmodel>"+
					"<iimptaxrate/>"+
					"<iexptaxrate/>"+
					"<bexpsale>1</bexpsale>"+
					"<idrawbatch/>"+
					"<bcheckbsatp>0</bcheckbsatp>"+
					"<cinvprojectcode/>"+
					"<itestrule/>"+
					"<crulecode/>"+
					"<bcheckfree1>0</bcheckfree1>"+
					"<bcheckfree2>0</bcheckfree2>"+
					"<bcheckfree3>0</bcheckfree3>"+
					"<bcheckfree4>0</bcheckfree4>"+
					"<bcheckfree5>0</bcheckfree5>"+
					"<bcheckfree6>0</bcheckfree6>"+
					"<bcheckfree7>0</bcheckfree7>"+
					"<bcheckfree8>0</bcheckfree8>"+
					"<bcheckfree9>0</bcheckfree9>"+
					"<bcheckfree10>0</bcheckfree10>"+
					"<bbommain>0</bbommain>"+
					"<bbomsub>0</bbomsub>"+
					"<bproductbill>0</bproductbill>"+
					"<icheckatp>0</icheckatp>"+
					"<iinvatpid/>"+
					"<iplantfday/>"+
					"<ioverlapday/>"+
					"<fmaxsupply/>"+
					"<bpiece>0</bpiece>"+
					"<bsrvitem>0</bsrvitem>"+
					"<bsrvfittings>0</bsrvfittings>"+
					"<fminsplit/>"+
					"<bspecialorder>0</bspecialorder>"+
					"<btracksalebill>0</btracksalebill>"+
					"<fbuyexcess/>"+
					"<isurenesstype>1</isurenesstype>"+
					"<idatetype/>"+
					"<idatesum/>"+
					"<idynamicsurenesstype/>"+
					"<ibestrowsum/>"+
					"<ipercentumsum/>"+
					"<binbyprocheck>1</binbyprocheck>"+
					"<irequiretrackstyle>0</irequiretrackstyle>"+
					"<ibomexpandunittype>1</ibomexpandunittype>"+
					"<iexpiratdatecalcu>0</iexpiratdatecalcu>"+
					"<bpurpricefree1>0</bpurpricefree1>"+
					"<bpurpricefree2>0</bpurpricefree2>"+
					"<bpurpricefree3>0</bpurpricefree3>"+
					"<bpurpricefree4>0</bpurpricefree4>"+
					"<bpurpricefree5>0</bpurpricefree5>"+
					"<bpurpricefree6>0</bpurpricefree6>"+
					"<bpurpricefree7>0</bpurpricefree7>"+
					"<bpurpricefree8>0</bpurpricefree8>"+
					"<bpurpricefree9>0</bpurpricefree9>"+
					"<bpurpricefree10>0</bpurpricefree10>"+
					"<bompricefree1>0</bompricefree1>"+
					"<bompricefree2>0</bompricefree2>"+
					"<bompricefree3>0</bompricefree3>"+
					"<bompricefree4>0</bompricefree4>"+
					"<bompricefree5>0</bompricefree5>"+
					"<bompricefree6>0</bompricefree6>"+
					"<bompricefree7>0</bompricefree7>"+
					"<bompricefree8>0</bompricefree8>"+
					"<bompricefree9>0</bompricefree9>"+
					"<bompricefree10>0</bompricefree10>"+
					"<bsalepricefree1>0</bsalepricefree1>"+
					"<bsalepricefree2>0</bsalepricefree2>"+
					"<bsalepricefree3>0</bsalepricefree3>"+
					"<bsalepricefree4>0</bsalepricefree4>"+
					"<bsalepricefree5>0</bsalepricefree5>"+
					"<bsalepricefree6>0</bsalepricefree6>"+
					"<bsalepricefree7>0</bsalepricefree7>"+
					"<bsalepricefree8>0</bsalepricefree8>"+
					"<bsalepricefree9>0</bsalepricefree9>"+
					"<bsalepricefree10>0</bsalepricefree10>"+
					"<finvoutuplimit/>"+
					"<bbondedinv>0</bbondedinv>"+
					"<bbatchcreate>0</bbatchcreate>"+
					"<bbatchproperty1>0</bbatchproperty1>"+
					"<bbatchproperty2>0</bbatchproperty2>"+
					"<bbatchproperty3>0</bbatchproperty3>"+
					"<bbatchproperty4>0</bbatchproperty4>"+
					"<bbatchproperty5>0</bbatchproperty5>"+
					"<bbatchproperty6>0</bbatchproperty6>"+
					"<bbatchproperty7>0</bbatchproperty7>"+
					"<bbatchproperty8>0</bbatchproperty8>"+
					"<bbatchproperty9>0</bbatchproperty9>"+
					"<bbatchproperty10>0</bbatchproperty10>"+
					"<bcontrolfreerange1>0</bcontrolfreerange1>"+
					"<bcontrolfreerange2>0</bcontrolfreerange2>"+
					"<bcontrolfreerange3>0</bcontrolfreerange3>"+
					"<bcontrolfreerange4>0</bcontrolfreerange4>"+
					"<bcontrolfreerange5>0</bcontrolfreerange5>"+
					"<bcontrolfreerange6>0</bcontrolfreerange6>"+
					"<bcontrolfreerange7>0</bcontrolfreerange7>"+
					"<bcontrolfreerange8>0</bcontrolfreerange8>"+
					"<bcontrolfreerange9>0</bcontrolfreerange9>"+
					"<bcontrolfreerange10>0</bcontrolfreerange10>"+
					"<finvciqexch/>"+
					"<iwarrantyperiod/>"+
					"<iwarrantyunit>0</iwarrantyunit>"+
					"<binvkeypart>1</binvkeypart>"+
					"<iacceptearlydays>999</iacceptearlydays>"+
					"<fcurllaborcost/>"+
					"<fcurlvarmanucost/>"+
					"<fcurlfixmanucost/>"+
					"<fcurlomcost/>"+
					"<fnextllaborcost/>"+
					"<fnextlvarmanucost/>"+
					"<fnextlfixmanucost/>"+
					"<fnextlomcost/>"+
					"<dinvcreatedatetime>"+head.getDinvcreatedatetime()+"</dinvcreatedatetime>"+
					"<bpuquota>0</bpuquota>"+
					"<binvrohs>0</binvrohs>"+
					"<fprjmatlimit/>"+
					"<bprjmat>0</bprjmat>"+
					"<binvasset>0</binvasset>"+
					"<bsrvproduct>0</bsrvproduct>"+
					"<iacceptdelaydays>0</iacceptdelaydays>"+
					"<cInvMnemCode/>"+
					"<iPlanCheckDay>0</iPlanCheckDay>"+
					"<iMaterialsCycle/>"+
					"<idrawtype>0</idrawtype>"+
					"<bSCkeyProjections>0</bSCkeyProjections>"+
					"<iSupplyPeriodType>1</iSupplyPeriodType>"+
					"<iTimeBucketId/>"+
					"<iAvailabilityDate>1</iAvailabilityDate>"+
					"<fmaterialcost/>"+
					"<inearrejectdays/>"+
					"<bimport>0</bimport>"+
					"<bsuitretail>0</bsuitretail>"+
					"<froundfactor>0</froundfactor>"+
					"<bchecksubitemcost>1</bchecksubitemcost>"+
					"<bconsiderfreestock>1</bconsiderfreestock>"+
					"<breceiptbydt>0</breceiptbydt>"+
					"<bkccutmantissa>0</bkccutmantissa>"+
					"</header>"+
					"<body>"+
					"<entry>"+
			        "<partid>1</partid>"+
			        "<invcode>"+head.getCode()+"</invcode>"+
			        "<free1/>"+
			        "<free2/>"+
			        "<free3/>"+
			        "<free4/>"+
			        "<free5/>"+
			        "<free6/>"+
			        "<free7/>"+
			        "<free8/>"+
			        "<free9/>"+
			        "<free10/>"+
			        "<safeqty/>"+
			        "<minqty/>"+
			        "<mulqty/>"+
			        "<fixqty/>"+
			        "<cbasengineerfigno/>"+
			        "<fbasmaxsupply/>"+
			        "<isurenesstype>1</isurenesstype>"+
			        "<idatetype/>"+
			        "<idatesum/>"+
			        "<idynamicsurenesstype/>"+
			        "<ibestrowsum/>"+
			        "<ipercentumsum/>"+
					"</entry>"+
					"</body>"+
					"</inventory>");
		}
			sb.append("</ufinterface>");
			
		return sb.toString();
	}
}